template_project/basic_app/urls.py
from django.urls import path,include
from basic_app import views

# Template Tagging Here!

app_name = 'basic_app'

urlpatterns= [
    path('relative/', views.relative, name = 'relative'),
    path('other/', views.other, name= 'other')
]

template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
]

template_project/basic_app/models.py
from django.db import models

# Create your models here.

template_project/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

template_project/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>



    <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top p">
        <div class="container">
            <ul class="nav navbar-nav">
                <li ><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="nav-item nav-link" href="{% url 'basic_app:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>
    
    <div class="container">
        <h1>?</h1>
        <h1>?</h1>
        {%block body_block%}
        <!-- This is where the body of each page will be. Outside of this will be inherited/universal html template!-->
        {%endblock%}
    </div>

</body>
</html>

template_project/templates/basic_app/index.html
<!DOCTYPE html>

{%extends "basic_app/base.html"%}
    {%block body_block%}

    <h1>Welcome to Index(Homepage)</h1>
    
    <h2>
        {{ text|cut:'world' }}
        {{ number|add:'69' }}
    </h2>

    
    {%endblock%}
    

template_project/templates/basic_app/other.html
{% load my_templates %}
<!DOCTYPE html>

{%extends "basic_app/base.html"%}
    {%block body_block%}

    <h1>Welcome to the Other Page</h1>
    
    {%endblock%}

template_project/templates/basic_app/relative_url_templates.html
{% load my_templates %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relative URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">Dis Link?</a>
    <a href="{%url 'admin:index' %} ">LInk to admin</a>
    <a href="{% url 'index' %} ">Link to Index</a>
</body>
</html>